FROM python:3.11

RUN apt-get update && apt-get install -yq tzdata

## 
RUN mkdir  /app-automatic-screening
COPY . /app-automatic-screening
RUN cd /app-automatic-screening && pip install --no-cache-dir -r requirements.txt
RUN python -m spacy download en_core_web_md

# RUN apt-get install --assume-yes git
WORKDIR /app-automatic-screening


# Run 
CMD ["uvicorn","app:app","--host","0.0.0.0","--port","5010","--reload"]
#CMD ["uvicorn","app:app","--port","5010", "--reload"]
